# action.yml
name: 'Codio assessment publish'
description: 'Publishes a new version of assessment'
inputs:
  token:
    description: 'API access token'
    required: false
  client-id:
    description: 'Client ID'
    required: false
  secret-id:
    description: 'Secret ID'
    required: false
  course-id:
    description: 'Course Id'
    required: true
  assignment-id:
    description: 'Assignement Id'
    required: true
  zip:
    description: 'Path to the zipped module or tar.gz archive'
    required: false
  dir:
    description: 'directory with the assignment files structure can be used instead of zip'
    required: false
  changelog:
    description: 'no message'
  domain:
    description: 'API Domain'
    default: 'codio.com'
runs:
  using: 'node12'
  main: 'dist/index.js'
